apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: stage-config-data-policies
policyDefaults:
  categories:
    - CM Configuration Management
  controls:
    - CM-1 Baseline Configuration
  namespace: policies
  remediationAction: inform
  severity: medium
policies:
- name: base-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./base/manifests
  placement:
    clusterSelectors:
      vendor: OpenShift
- name: stage-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./manifests
  placement:
    clusterSelectors:
      env: stage
