apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: stage-config-data-policies
policyDefaults:
  categories:
    - CM Configuration Management
  controls:
    - CM-1 Baseline Configuration
  namespace: policies
  remediationAction: inform
  severity: medium
  placement:
    clusterselector:
      env: stage
policies:
- name: base-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ../../base/manifests
- name: stage-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./manifests
