apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: enforce-config-policies
policyDefaults:
  categories:
    - CM Configuration Management
  controls:
    - CM-1 Baseline Configuration
  namespace: policies
  remediationAction: enforce
  severity: medium
policies:
- name: stage-configs
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./common/stage/manifests
  placement:
    clusterSelectors:
      env: stage
      vendor: OpenShift
- name: prod-configs
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./common/prod/manifests
  placement:
    clusterSelectors:
      env: prod
      vendor: OpenShift
