apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: stage-config-data-policies
policyDefaults:
  categories:
    - CM Configuration Management
  controls:
    - CM-1 Baseline Configuration
  namespace: policies
  remediationAction: inform
  severity: medium
policies:
- name: base-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./common/base/manifests
  placement:
    clusterSelectors:
      vendor: OpenShift
- name: stage-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./common/stage/manifests
      patches:
        - apiVersion: "operator.openshift.io/v1"
          kind: "IngressController"
          metadata:
            name: "default"
            namespace: "openshift-ingress-operator"
          spec:
            replicas: 2
  placement:
    clusterSelectors:
      env: stage
- name: prod-configurations
  categories:
    - setup
  controls:
    - setup
  disabled: false
  manifests:
    - path: ./common/prod/manifests
  placement:
    clusterSelectors:
      env: prod
