apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
#    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  name: router-cloudapps
  namespace: openshift-ingress

