apiVersion: v1
kind: Namespace
metadata:
  name: policy-generator
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policy-generator-placementrules
  namespace: policy-generator
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - policy-generator-placementrules
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: policy-generator-placementrules
  namespace: policy-generator
spec:
  type: Git
  pathname: 'https://github.com/amigliet/rhacm-policygen.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: placementrules
    apps.open-cluster-management.io/git-path: /
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policy-generator-placementrules
  name: policy-generator-subscription-placementrules
  namespace: policy-generator
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: policy-generator/policy-generator-placementrules
  placement:
    placementRef:
      kind: PlacementRule
      name: policy-generator-placementrules-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: policy-generator-placementrules
  name: policy-generator-placementrules-placement
  namespace: policy-generator
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
